<?php
$pagetitle = "Account options";
include_once ('header.php');
if (isset($_SESSION['userid'])){
    $preference_message = '';
    $import_preview = null;
    include_once (__DIR__ . '/includes/title-json-import.php');
    if (isset($_POST['apply_title_import'])) {try {$preview=json_decode(base64_decode((string)($_POST['import_preview']??''),true),true,32,JSON_THROW_ON_ERROR);if(!is_array($preview)||empty($preview['character'])||!isset($preview['changes']))throw new RuntimeException('The import preview expired or was invalid. Please upload the JSON again.');$count=gwttt_title_import_apply($con,(int)$_SESSION['userid'],$preview);$preference_message='Imported '.$count.' title update'.($count===1?'':'s').' for '.$preview['character']['charname'].'.';}catch(Throwable $e){$preference_message='Title import failed: '.$e->getMessage();}}
    elseif(isset($_POST['preview_title_import'])){try{$import_preview=gwttt_title_import_load($con,(int)$_SESSION['userid'],$_FILES['title_json']??array());}catch(Throwable $e){$preference_message='Title import preview failed: '.$e->getMessage();}}
    if(isset($_POST['save_email_preferences'])){$birthday_email_enabled=isset($_POST['birthday_email_enabled'])?1:0;$birthday_reminder_days=(int)($_POST['birthday_reminder_days']??0);$treasure_email_enabled=isset($_POST['treasure_email_enabled'])?1:0;if(!in_array($birthday_reminder_days,array(0,1,3,7),true))$birthday_reminder_days=0;$prefstmt=$con->prepare("INSERT INTO user_preferences (userid,birthday_email_enabled,birthday_reminder_days,treasure_email_enabled) VALUES (?,?,?,?) ON DUPLICATE KEY UPDATE birthday_email_enabled=VALUES(birthday_email_enabled),birthday_reminder_days=VALUES(birthday_reminder_days),treasure_email_enabled=VALUES(treasure_email_enabled)");$prefstmt->bind_param("iiii",$_SESSION['userid'],$birthday_email_enabled,$birthday_reminder_days,$treasure_email_enabled);$preference_message=$prefstmt->execute()?'E-mail reminder preferences updated.':'Unable to update e-mail reminder preferences.';$prefstmt->close();}
    if(!empty($_POST['useremail']))include_once('includes/update-email.php');if(!empty($_POST['oldpass']))include_once('includes/update-password.php');if(!empty($_POST['setacc']))include_once('includes/set-prefacc.php');if(!empty($_POST['setchar']))include_once('includes/set-prefchar.php');
    echo '<section class="options-page"><h3>Set preferred account &amp; character, import titles, or change account settings</h3>';if($preference_message!=='')echo '<p class="options-message"><strong>'.h($preference_message).'</strong></p>';
    echo '<fieldset class="options-card account-options-card"><legend>Account &amp; character</legend><form action="preferences.php" method="post" class="options-form">'.csrf_input().'<div class="options-current">Current preferred account: <strong>'.h($_SESSION['prefaccname']).'</strong></div><div class="options-control-row"><select name="prefaccid"><option value="nopref">Prefer no default</option>';$prefacc=$con->prepare("SELECT accid,accemail FROM gwaccounts WHERE userid=?");$prefacc->bind_param("i",$_SESSION['userid']);$prefacc->execute();$resacc=$prefacc->get_result();while($row=$resacc->fetch_assoc())echo '<option value="'.(int)$row['accid'].'">'.h($row['accemail']).'</option>';$prefacc->close();echo '</select><button type="submit">Set account</button></div><input type="hidden" name="setacc" value="update"></form>';
    echo '<form action="preferences.php" method="post" class="options-form">'.csrf_input().'<div class="options-current">Current preferred character: <strong>'.h($_SESSION['prefcharname']).'</strong></div><div class="options-control-row"><select name="prefcharid"><option value="nopref">Prefer no default</option>';$prefchar=$con->prepare("SELECT charid,charname FROM gwchars WHERE accid=? AND userid=?");$prefchar->bind_param("ii",$_SESSION['prefaccid'],$_SESSION['userid']);$prefchar->execute();$reschar=$prefchar->get_result();while($row2=$reschar->fetch_assoc())echo '<option value="'.(int)$row2['charid'].'">'.h($row2['charname']).'</option>';$prefchar->close();echo '</select><button type="submit">Set character</button></div><input type="hidden" name="setchar" value="updatechar"></form><form action="preferences.php" method="post" class="options-form options-email-form">'.csrf_input().'<label for="useremail">Update e-mail address</label><div class="options-control-row"><input id="useremail" type="email" name="useremail" maxlength="50" value="'.h($_SESSION['usermail']).'" required><button type="submit">Update e-mail</button></div></form></fieldset>';
    echo '<fieldset class="options-card import-options-card"><legend>Import Guild Wars titles</legend><p class="import-help">Upload <strong>GWTTT-Titles.json</strong> created by the GWTTT Toolbox exporter. GWTTT matches the character name in the export to one of your registered characters, then routes account-wide and character-wide title progress automatically.</p><form action="preferences.php" method="post" enctype="multipart/form-data" class="options-form import-form">'.csrf_input().'<input type="file" name="title_json" accept="application/json,.json" required><button type="submit" name="preview_title_import" value="1">Preview import</button></form>';
    if($import_preview){$c=$import_preview['character'];$changes=$import_preview['changes'];$account_count=0;$char_count=0;$decrease_count=0;foreach($changes as $change){if((int)$change['type']===0)$account_count++;else$char_count++;if($change['old']!==null&&(int)$change['new']<(int)$change['old'])$decrease_count++;}echo '<div class="import-preview"><p><strong>Target:</strong> '.h($c['charname']).' on '.h($c['accemail']).'</p><p><strong>'.count($changes).'</strong> changes: '.$account_count.' account-wide, '.$char_count.' character-wide.</p>';if($decrease_count>0)echo '<p class="import-decrease-warning"><strong>Warning:</strong> This export contains '.$decrease_count.' value'.($decrease_count===1?'':'s').' lower than the progress currently stored in GWTTT. Review the downward changes marked below before importing.</p>';
        if($changes){echo '<div class="import-table-wrap"><table class="import-table"><thead><tr><th>Title</th><th>Scope</th><th>Current</th><th>Imported</th></tr></thead><tbody>';foreach($changes as $change){$pct=!empty($change['percentage_based']);$format=function($v)use($pct){if($v===null)return 'Not tracked';return $pct?number_format(((int)$v)/10,1).'%':number_format((int)$v);};$decrease=$change['old']!==null&&(int)$change['new']<(int)$change['old'];echo '<tr'.($decrease?' class="import-decrease"':'').'><td>'.h($change['name']).'</td><td>'.((int)$change['type']===0?'Account':'Character').'</td><td>'.$format($change['old']).'</td><td>'.$format($change['new']).($decrease?' <strong class="import-down" aria-label="decrease">&darr;</strong>':'').'</td></tr>';}echo '</tbody></table></div>';$encoded=base64_encode(json_encode($import_preview,JSON_UNESCAPED_SLASHES));echo '<form action="preferences.php" method="post" class="import-confirm">'.csrf_input().'<input type="hidden" name="import_preview" value="'.h($encoded).'"><button type="submit" name="apply_title_import" value="1">Import these '.count($changes).' changes</button></form>';}else echo '<p>No title values need updating.</p>';
        if($import_preview['skipped']){echo '<details class="import-skipped"><summary>Skipped '.count($import_preview['skipped']).' export entries</summary><table class="import-table"><thead><tr><th>Title</th><th>Reason</th></tr></thead><tbody>';foreach($import_preview['skipped'] as $skip)echo '<tr><td>'.h($skip['name']).'</td><td>'.h($skip['reason']).'</td></tr>';echo '</tbody></table></details>';}echo '</div>';}
    echo '</fieldset>';
    $birthday_email_enabled=0;$birthday_reminder_days=0;$treasure_email_enabled=0;$prefquery=$con->prepare("SELECT birthday_email_enabled,birthday_reminder_days,treasure_email_enabled FROM user_preferences WHERE userid=?");$prefquery->bind_param("i",$_SESSION['userid']);$prefquery->execute();$prefresult=$prefquery->get_result();if($prefrow=$prefresult->fetch_assoc()){$birthday_email_enabled=(int)$prefrow['birthday_email_enabled'];$birthday_reminder_days=(int)$prefrow['birthday_reminder_days'];$treasure_email_enabled=(int)$prefrow['treasure_email_enabled'];}$prefquery->close();echo '<form action="preferences.php" method="post">'.csrf_input().'<fieldset class="birthday-preferences"><legend>E-mail reminders</legend><label class="birthday-toggle"><input type="checkbox" name="birthday_email_enabled" value="1"'.($birthday_email_enabled===1?' checked':'').'><span>E-mail me reminders for my characters\' birthdays</span></label><div class="birthday-reminder-row"><label for="birthday_reminder_days">Send reminder</label><select id="birthday_reminder_days" name="birthday_reminder_days">';foreach(array(0=>'on the birthday',1=>'1 day before',3=>'3 days before',7=>'7 days before')as$days=>$label)echo '<option value="'.$days.'"'.($birthday_reminder_days===$days?' selected':'').'>'.h($label).'</option>';echo '</select></div><label class="birthday-toggle"><input type="checkbox" name="treasure_email_enabled" value="1"'.($treasure_email_enabled===1?' checked':'').'><span>E-mail me when my characters\' treasures are ready to collect again</span></label><p class="birthday-help">Treasure reminders use a 31-day buffer after the most recent collection.</p><input type="hidden" name="save_email_preferences" value="1"><button type="submit">Save e-mail preferences</button><p class="birthday-help">Birthday and treasure reminders are disabled unless you explicitly opt in.</p></fieldset></form>';
    echo '<fieldset class="options-card password-options-card"><legend>Change password</legend><form action="preferences.php" method="post" class="password-options-form">'.csrf_input().'<label for="oldpass">Current password</label><input type="password" name="oldpass" id="oldpass" autocomplete="current-password" required><label for="up1">New password</label><input type="password" name="userpass1" id="up1" minlength="8" maxlength="255" autocomplete="new-password" required><label for="up2">Verify new password</label><input type="password" name="userpass2" id="up2" minlength="8" maxlength="255" autocomplete="new-password" required><button type="submit" name="submission" id="btnSubmit">Update password</button></form></fieldset>';
?>
<script>document.getElementById("btnSubmit").addEventListener("click",function(e){if(document.getElementById("up1").value!==document.getElementById("up2").value){e.preventDefault();alert("Passwords do not match.");}});</script>
<style>.options-page{width:min(100%,760px);margin:0 auto;text-align:center}.options-page>h3{margin:10px 0 24px}.options-card{width:min(100%,560px);margin:28px auto 10px;padding:18px 20px 20px;border:1px solid #2d6978;border-radius:7px;background:#122936;text-align:left}.options-card legend{padding:0 8px;color:#69dbe1;font-size:17px}.options-card label{float:none;width:auto;margin:0;padding:0;text-align:left}.options-form{width:100%;margin:0 0 22px}.options-current,.options-email-form>label{display:block;margin-bottom:8px;color:#dce8ee;font-weight:600}.options-current strong{color:#f3e3bd}.options-control-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;align-items:center}.options-control-row select,.options-control-row input,.password-options-form input,.import-form input{width:100%;min-height:38px;padding:6px 10px;border:1px solid #547080;border-radius:5px;background:#edf2f5;color:#17242c;font:15px "Segoe UI",Tahoma,Arial,sans-serif}.options-card button{min-height:38px;padding:7px 14px;border:1px solid #2999a5;border-radius:4px;background:#174454;color:#fff;font-weight:600;cursor:pointer}.password-options-form{display:grid;grid-template-columns:150px minmax(0,1fr);gap:12px 14px;align-items:center}.password-options-form button{grid-column:2;justify-self:start}.import-help,.import-note{color:#b9ccd5;line-height:1.45}.import-form{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;align-items:center}.import-preview{margin-top:18px;padding-top:14px;border-top:1px solid #285367}.import-table-wrap{max-height:360px;overflow:auto;margin:12px 0}.import-table{width:100%;border-collapse:collapse;font-size:13px}.import-table th,.import-table td{padding:6px 8px;border-bottom:1px solid #285367;text-align:left;white-space:nowrap}.import-table th{color:#69dbe1}.import-confirm{margin-top:14px}.import-skipped{margin-top:18px;color:#b9ccd5}.import-skipped summary{cursor:pointer;color:#69dbe1;font-weight:600}.import-decrease-warning{margin:12px 0;padding:10px 12px;border:1px solid #b8863b;border-radius:5px;background:#392d1d;color:#ffe0a3;line-height:1.4}.import-decrease td{background:#2a2520}.import-down{color:#ffbf69;font-size:16px}.options-message{padding:10px;border:1px solid #2d6978;border-radius:5px;background:#122936}.birthday-preferences{margin-top:28px}@media(max-width:600px){.options-control-row,.password-options-form,.import-form{grid-template-columns:1fr}.password-options-form button{grid-column:1}.options-control-row button,.password-options-form button,.import-form button{width:100%}}</style>
<?php echo '</section>';}
include_once ('footer.php');
?>